theme: jekyll-theme-minimal
title: Hello World! 
description: 
<script> document.cookie = "session=test GDPR"; 
document.cookie = "favorite_task=collect Data"; 
function alertCookie() { alert(document.cookie); } 
</script>
