remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
title: Lorena & Iulia  cookie site
description: Bookmark this to keep an eye on my project updates!
