remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: Lorena & Iulia  cookie site
description: Bookmark this to keep an eye on my project updates!
document.cookie = "session=test GDPR" 
document.cookie = "favorite_task=collect Data"
function alertCookie() { alert(document.cookie); } 
<body> Bine ai venit la lab <button onclick="alertCookie()">Show cookies</button> </body>
